# Generated by Django 4.1.5 on 2023-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alluser_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='age',
            field=models.IntegerField(null=True, verbose_name='age'),
        ),
    ]
