# Generated by Django 4.1.5 on 2023-03-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_prescription_appointment_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
    ]
