# Generated by Django 4.1.5 on 2023-03-14 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0006_appointment_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]